# Assemble the Overleaf / submission package.
#
# Ships only what the journal asks for, in the file split its double-anonymized
# process requires:
#
#   titlepage.tex   identifying information, uploaded as a separate file
#   main.tex        the anonymized manuscript
#   highlights.txt  3-5 bullets, uploaded as its own file with "highlights" in
#                   the name, per the guide
#   references.bib  numbered style, order of first appearance
#
# Figures are the tracked artefacts in paper/figures/, regenerated by
# `funnel-shap figures`. Only figures the manuscript actually cites are staged:
# the journal counts figures against the 34-page limit and does not accept
# supplementary material without the Editor-in-Chief's consent, so an unused
# figure has nowhere to live.
#
#   pwsh -File build_zip.ps1

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$staging = Join-Path ([System.IO.Path]::GetTempPath()) "funnel_shap_submission"
$out = Join-Path (Split-Path -Parent $here) "funnel_shap_overleaf.zip"

if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
New-Item -ItemType Directory -Path (Join-Path $staging "figures") -Force | Out-Null

foreach ($f in @("main.tex", "titlepage.tex", "highlights.txt", "references.bib", "README.md")) {
    Copy-Item (Join-Path $here $f) $staging
}

# Stage exactly the figures cited by the manuscript.
$tex = Get-Content (Join-Path $here "main.tex") -Raw
$cited = [regex]::Matches($tex, '\\includegraphics\[[^\]]*\]\{([^}]+)\}') |
         ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
$figdir = Join-Path (Split-Path -Parent $here) "figures"
foreach ($fig in $cited) {
    $src = Join-Path $figdir $fig
    if (-not (Test-Path $src)) { throw "manuscript cites $fig but it is not in $figdir" }
    Copy-Item $src (Join-Path $staging "figures")
}
Write-Output ("staged {0} cited figures: {1}" -f $cited.Count, ($cited -join ", "))

if (Test-Path $out) { Remove-Item $out -Force }
Compress-Archive -Path "$staging\*" -DestinationPath $out
Remove-Item $staging -Recurse -Force

Write-Output "-> $out"
