# Assemble the Overleaf upload package.
#
# The figures are not duplicated in this directory: they are the tracked
# artefacts in paper/figures/, regenerated by `funnel-shap figures`. This
# script stages them alongside the sources and zips the result.
#
#   pwsh -File build_zip.ps1

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$staging = Join-Path ([System.IO.Path]::GetTempPath()) "funnel_shap_submission"
$out = Join-Path (Split-Path -Parent $here) "funnel_shap_overleaf.zip"

if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }
New-Item -ItemType Directory -Path (Join-Path $staging "figures") -Force | Out-Null

Copy-Item (Join-Path $here "main.tex")       $staging
Copy-Item (Join-Path $here "references.bib") $staging
Copy-Item (Join-Path $here "README.md")      $staging
Copy-Item (Join-Path (Split-Path -Parent $here) "figures\*.pdf") (Join-Path $staging "figures")

if (Test-Path $out) { Remove-Item $out -Force }
Compress-Archive -Path "$staging\*" -DestinationPath $out
Remove-Item $staging -Recurse -Force

Write-Output "-> $out"
